server:
  port: 8888

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  application:
    name: config-serive
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dinhdiepvuong/configserver-microservice.git
          default-label: main
          username:
          password:
          skip-ssl-validation: true
          ignore-local-ssh-settings: true
        bootstrap: true